server:
  port: 8088
  servlet:
    path: /
logging:
  level:
    cn.itcast: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test2020
    username: root
    password: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  type-aliases-package: cn.itcast.pojo
#  mapper-locations: mapper/*.xml
